/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-01 18:14:47 UTC)
 * on 2014-04-04 at 19:00:50 UTC 
 * Modify at your own risk.
 */

package com.islandturtlewatch.nest.reporter.transport.reportEndpoint.model;

/**
 * Model definition for ReportRef.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the reportEndpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ReportRef extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String refEncoded;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRefEncoded() {
    return refEncoded;
  }

  /**
   * @param refEncoded refEncoded or {@code null} for none
   */
  public ReportRef setRefEncoded(java.lang.String refEncoded) {
    this.refEncoded = refEncoded;
    return this;
  }

  @Override
  public ReportRef set(String fieldName, Object value) {
    return (ReportRef) super.set(fieldName, value);
  }

  @Override
  public ReportRef clone() {
    return (ReportRef) super.clone();
  }

}
