/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-03-31 at 04:46:09 UTC 
 * Modify at your own risk.
 */

package com.islandturtlewatch.nest.reporter.transport.reportEndpoint.model;

/**
 * Model definition for ReportRef.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the reportEndpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ReportRef extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ref;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public ReportRef setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @see #decodeRef()
   * @return value or {@code null} for none
   */
  public java.lang.String getRef() {
    return ref;
  }

  /**

   * @see #getRef()
   * @return Base64 decoded value or {@code null} for none
   *
   * @since 1.14
   */
  public byte[] decodeRef() {
    return com.google.api.client.util.Base64.decodeBase64(ref);
  }

  /**
   * @see #encodeRef()
   * @param ref ref or {@code null} for none
   */
  public ReportRef setRef(java.lang.String ref) {
    this.ref = ref;
    return this;
  }

  /**

   * @see #setRef()
   *
   * <p>
   * The value is encoded Base64 or {@code null} for none.
   * </p>
   *
   * @since 1.14
   */
  public ReportRef encodeRef(byte[] ref) {
    this.ref = com.google.api.client.util.Base64.encodeBase64URLSafeString(ref);
    return this;
  }

  @Override
  public ReportRef set(String fieldName, Object value) {
    return (ReportRef) super.set(fieldName, value);
  }

  @Override
  public ReportRef clone() {
    return (ReportRef) super.clone();
  }

}
